name: Test

on: [ workflow_dispatch ]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: DRONE
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        uses: gradle/gradle-build-action@v2.1.5
        env:
          DRONE_CERT: ${{ secrets.DRONE_CERT }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ROOT_CA: ${{ secrets.ROOT_CA }}
        with:
          arguments: build