name: OpenAPI Validation

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
    tags:
      - '*'
    paths:
      - 'src/main/resources/**.json'
  pull_request:
  workflow_dispatch:

jobs:
  List-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0
      - name: List files
        uses: mirko-felice/list-files-action@v2.0.0
        with:
          path: "src/main/resources"
          ext: "*.json"

  Validation:
    needs: List-Files
    strategy:
      fail-fast: false
      matrix:
        paths: ${{ fromJson(needs.List-Files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: ${{ matrix.paths }}