name: OpenAPI Validation

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
    tags:
      - '*'
    paths:
      - 'src/main/resources/**.json'
  pull_request:

jobs:
  Setup-Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.Set-Matrix.outputs.matrix }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - id: Set-Matrix
        run: |
          matrix=$(( echo '{ "definition-file" : ['
            cd src/main/resources/
            find -name *.json | paste -sd ,
            cd ../../..
            echo " ]}"
          ) | jq -c .)
          echo $matrix
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix"

  Check-Matrix:
    runs-on: ubuntu-latest
    needs: Setup-Matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.Setup-Matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  Validation:
    needs: Setup-Matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.SetupMatrix.outputs.matrix) }}
    runs-on: ubuntu-latest

    steps:
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: ${{ matrix.definition-file }}