name: OpenAPI Validation

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
    tags:
      - '*'
    paths:
      - 'src/main/resources/**.json'
  pull_request:
  workflow_dispatch:

jobs:
  Get-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0
      - name: Path lister action
        uses: Rishabh510/Path-lister-action@1.0
        with:
          path: "src/main/resources/**"
          type: "*.json"

  Validation:
    needs: Get-Files
    strategy:
      fail-fast: false
      matrix: ${{ needs.Get-Files.outputs.paths }}
    runs-on: ubuntu-latest

    steps:
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: ${{ matrix.definition-file }}